{
  FailureCloseableIterator it=new FailureCloseableIterator();
  try {
    it.next();
    fail();
  }
 catch (  IllegalStateException expected) {
    assertThat(expected).hasMessage("expected failure");
    assertThat(it.isClosed).isTrue();
  }
}
