{
  SQLException root=new SQLException("this is root","123");
  SQLException next=new SQLException("this is next","456");
  root.setNextException(next);
  DatabaseUtils.log(Loggers.get(getClass()),root);
  assertThat(logTester.logs(LoggerLevel.ERROR)).contains("SQL error: 456. Message: this is next");
}
