{
  exception.expect(NullPointerException.class);
  exception.expectMessage("start() method has not been called");
  underTest.getStartedAt();
}
